#!/bin/bash
set -e
M=Main
S=$M.sugar
J=$M.java

function sugarc {
  sugarhead | sed -e 's/^# /#define /'
  echo "public class $M {"
  echo "  public static Scanner scan = new Scanner(System.in);"
  cat $S | \
    sugarptpl | \
    sugarpctr | \
    sugarplop | \
    sugarpdbg | \
    sed -E -e 's,^\{,void main(String[] args) {,' \
           -e 's,^([^ {}]),public static \1,' \
           -e 's,(class ([^ {]*).*\{),\1\n#undef CLS\n#define CLS \2,' \
           -e 's,^  (\(.*\) *\{),  .CLS\1,' \
           -e 's,  \.,  public ,' \
           -e 's,^,  ,g'
  echo }
}

sugarc > .rawsugar
cpp -P .rawsugar | sed -e 's/ , /, /g' -e 's/ ;/;/g' -e 's/__//g' > $J
myjavac $J || (cat -n $J && false)
echo Running...
myjava $M || (cat -n $J && false)
