#!/usr/bin/python2
import sys,os,re
indent="  "
def f(m):
  args = [s.split() for s in re.split(', *', m.group(1))]
  out = '\n'.join(indent+'.{} {};\n'.format(*arg) for arg in args)
  astr = ', '.join(t+' '+n+'_' for (t,n) in args)
  bstr = ' '.join(n+'='+n+'_;' for (t,n) in args)
  return out+indent+'('+astr+') { '+bstr+' }\n'
for l in list(sys.stdin):
  print re.sub(r'^  \(([^)]*)\);', f, l[:-1])

