#!/bin/bash
set -e
J=Main.java

function sugarc {
  sugarhead | sed -e 's/# /#define /'
  echo 'public class Main {'
  echo '  public static Scanner scan = new Scanner(System.in);'
  cat Main.sugar | \
    sugarptpl | \
    sugarpctr | \
    sugarplop | \
    sugarpdbg | \
    sed -E -e 's,^\{,void main(String[] args) {,' \
           -e 's,^([^ {}]),public static \1,' \
           -e 's,(class ([^ ]*).*\{),\1\n#undef CLS\n#define CLS \2,' \
  `#space` -e 's,^  (\(.*?\)),  .CLS\1,' \
  `#space` -e 's,  \.,  public ,' \
           -e 's,^,  ,'
  echo }
}

sugarc > .rawsugar
cpp -P .rawsugar | sed -e 's/ , /, /g' -e 's/ ;/;/g' -e 's/__//g' > $J
myjavac $J || (cat -n $J && false)
echo Running...
myjava Main || (cat -n $J && false)
