#!/usr/bin/python2
import sys, re, os
def f(m):
  v = '_ijklou'[len(m.group(1))/2]
  return m.group(1)+'for ('+v+','+m.group(2)+') {'
for l in sys.stdin:
  print re.sub(r"^( *)loop *\((.*)\) *\{", f, l[:-1])
